# This is a GitHub Actions workflow that performs several tasks
name: Create SUB Folder

# The workflow will run when there is a push to the `main` branch
on:
  push:
    branches:
      - main

# The workflow will also run on a schedule, every 120 minutes
  schedule:
  - cron: '*/120 * * * *'

# Defines a job named `build`
jobs:
  build:
    # Specifies that the job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository code using the `actions/checkout@v2` action
      - name: Check out repository code
        uses: actions/checkout@v3

      # Sets up Git by configuring the user name and email
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"

      # Removes all files from the `SUB` folder if it exists
      - name: Remove files from SUB folder
        run: |
          if [ -d "SUB" ]; then
            rm -rf SUB/*
          fi

      # Downloads a file from a URL using `curl`
      - name: Download file from URL
        run: |
          curl "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/reality" | tail -n +7 > file.txt

      - name: Install regex module
        run: pip install regex

      # Creates the `SUB` directory if it doesn't exist
      - name: Create SUB directory
        run: mkdir SUB

      # Loop through Users.txt and create files based on the content
      - name: Create files from Users.txt
        run: |
          while IFS=, read -r name value; do
            if [ "$value" -gt 0 ]; then
              echo "vless://64694d4a-2c05-4ffe-aef1-68c0169cccb7@146.248.115.39:443?encryption=none&fp=firefox&mode=gun&pbk=TXpA-KUEqsg6YlZUXf0gZIe14rFjKZZNAqWzjruNoh8&security=reality&serviceName=&sid=790d3c76&sni=www.speedtest.net&spx=%2F&type=grpc#|ðŸ‘¤User:$name|âŒ›ï¸Remain Days:$value|" > "SUB/REALITY-$name"
            fi
          done < Users.txt

      # Adds, commits, and pushes changes to the `SUB` folder.
      - name: Commit and push changes
        run: |
           git config --global user.name 'GitHub Action'
           git config --global user.email 'action@github.com'
           git add .
           git commit -m "Updated"
           git pull origin main --rebase # <-- Added --rebase flag here to fix the error.
           git push origin main
